### ISSUE TITLE
Keys sometimes ignored

### ISSUE THREAD

**Issue by EricShapiro** [BalestraPatrick/AppleWatchCalculator#3]
When I press a number key, the number doesn't always update, especially when it is the 2nd or later key in a sequence. I'm not sure why yet - the call below is being made with the correct string, but the watch screen doesn't refresh.

    [self.resultLabel setText:self.displayString];

**Comment by BalestraPatrick** [comment]
Thanks for the issue. I just checked the code and indeed it doesn't work. I think there is a bug in WatchKit when updating the text of a label with a NSMutableString so I replaced it with a NSString which works as expected (just pushed the fix). I'm going to open a radar about it right now :)

**Comment by EricShapiro** [comment]
Good deduction. If you mutate the string after setting it the mutated version shows up. Apple should add a -copy call in the setter as a fix. I suspect part of the issue is that WatchKit doesn't actually refresh the string until the next runloop.

**Comment by BalestraPatrick** [comment]
<a href="https://openradar.appspot.com/radar?id=5036905917841408">rdar://20352130</a>
